# Generated by Django 3.2.9 on 2025-12-09 16:27

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodSconto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codice', models.CharField(max_length=50)),
                ('sconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentuale', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('inizioValidita', models.DateField(default=django.utils.timezone.now)),
                ('fineValidita', models.DateField()),
                ('usi', models.IntegerField(default=0)),
                ('massimoUsi', models.IntegerField(default=1)),
            ],
        ),
    ]
