# Generated by Django 3.2.9 on 2025-12-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('bday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('weight', models.CharField(max_length=15, null=True)),
                ('height', models.CharField(max_length=15, null=True)),
                ('training_exp', models.CharField(max_length=255, null=True)),
                ('coach_exp', models.TextField()),
                ('skills', models.CharField(max_length=255, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('video', models.CharField(max_length=255, null=True)),
                ('max_coaching', models.IntegerField(default=8)),
            ],
        ),
    ]
