# Generated by Django 3.2.9 on 2025-12-09 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheda_tutorial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='level_course',
            field=models.ManyToManyField(related_name='coaches', to='scheda_tutorial.LevelCourse'),
        ),
        migrations.AddField(
            model_name='coach',
            name='top_discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scheda_tutorial.discipline'),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='coach',
            constraint=models.UniqueConstraint(fields=('name', 'surname', 'bday'), name='coach_coach_unique'),
        ),
    ]
