# Generated by Django 3.2.9 on 2025-12-09 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title_description', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('image', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('G', 'Generic')], default='M', max_length=10)),
                ('type', models.CharField(choices=[('T', 'Tutorial'), ('C', 'Customized')], default='C', max_length=10)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('coaches', models.ManyToManyField(to='coach.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('repetitions', models.CharField(max_length=50)),
                ('series', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('load', models.CharField(blank=True, max_length=50, null=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('exe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheda_tutorial.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='FormSP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Scheda X', max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('first_published', models.DateField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('feedback', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_pers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormST',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('personalization', models.TextField(blank=True, null=True)),
                ('coach_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField()),
                ('formSP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='scheda_tutorial.formsp')),
                ('formST', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='scheda_tutorial.formst')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuperSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('repetitions', models.CharField(max_length=50)),
                ('stop', models.IntegerField()),
                ('load', models.CharField(blank=True, max_length=50, null=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('exe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheda_tutorial.exercise')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_series', to='scheda_tutorial.exerciseinform')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scheda_tutorial.day')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scheda_tutorial.survey')),
            ],
        ),
        migrations.CreateModel(
            name='LevelCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('PRIMI_PASSI', 'Primi Passi'), ('BASE', 'Base'), ('INTERMEDIO', 'Intermedio'), ('AVANZATO', 'Avanzato'), ('MASTER', 'Master')], default='PRIMI_PASSI', max_length=11)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('requirements', models.TextField()),
                ('goals', models.TextField()),
                ('goals_video', models.CharField(max_length=255, null=True)),
                ('frequency', models.CharField(default='Ogni giorno', max_length=255)),
                ('duration', models.CharField(default='4 Settimane', max_length=255)),
                ('required_items', models.TextField()),
                ('requirements_video', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('video', models.CharField(default='NON PRESENTE', max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='scheda_tutorial.course')),
            ],
        ),
        migrations.AddField(
            model_name='formst',
            name='scheda_tutorial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form', to='scheda_tutorial.levelcourse'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='settimanale', max_length=50)),
                ('critici', models.TextField(blank=True, null=True)),
                ('forti', models.TextField(blank=True, null=True)),
                ('ese_differenti', models.TextField(blank=True, null=True)),
                ('tempistiche_ok', models.TextField(blank=True, null=True)),
                ('altro', models.TextField(blank=True, null=True)),
                ('inviato', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('da_inviare', models.DateField(blank=True, null=True)),
                ('token', models.CharField(max_length=100)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_recived', to='scheda_tutorial.formsp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback_recived', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exerciseinform',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='scheda_tutorial.section'),
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='scheda_tutorial.week'),
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='scheda_tutorial.discipline'),
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('scheda_tutorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='scheda_tutorial.levelcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schede_tutorial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='levelcourse',
            constraint=models.UniqueConstraint(fields=('level', 'gender', 'course'), name='scheda_tutorial_levelcourse_unique'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('name', 'gender', 'type'), name='scheda_tutorial_exercise_unique'),
        ),
        migrations.AddConstraint(
            model_name='association',
            constraint=models.UniqueConstraint(fields=('user', 'scheda_tutorial'), name='scheda_tutorial_association_unique'),
        ),
    ]
